In [3]:
%load_ext sql

In [4]:
%sql postgresql://student:student@127.0.0.1/sparkifydb

'Connected: student@sparkifydb'

In [5]:
%sql SELECT * FROM songplays LIMIT 5;

 * postgresql://student:***@127.0.0.1/sparkifydb
5 rows affected.

[(1, datetime.datetime(2018, 11, 29, 0, 0, 57, 796000), '73', 'paid', None, None, 954, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (2, datetime.datetime(2018, 11, 29, 0, 1, 30, 796000), '24', 'paid', None, None, 984, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (3, datetime.datetime(2018, 11, 29, 0, 4, 1, 796000), '24', 'paid', None, None, 984, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (4, datetime.datetime(2018, 11, 29, 0, 4, 55, 796000), '73', 'paid', None, None, 954, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (5, datetime.datetime(2018, 11, 29, 0, 7, 13, 796000), '24', 'paid', None, None, 984, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"')]

In [6]:
%sql SELECT * FROM users LIMIT 5;

 * postgresql://student:***@127.0.0.1/sparkifydb
5 rows affected.

[('73', 'Jacob', 'Klein', 'M     ', 'paid'),
 ('24', 'Layla', 'Griffin', 'F     ', 'paid'),
 ('50', 'Ava', 'Robinson', 'F     ', 'free'),
 ('54', 'Kaleb', 'Cook', 'M     ', 'free'),
 ('32', 'Lily', 'Burns', 'F     ', 'free')]

In [7]:
%sql SELECT * FROM songs LIMIT 5;

 * postgresql://student:***@127.0.0.1/sparkifydb
5 rows affected.

[('SOINLJW12A8C13314C', 'City Slickers', 'AR8IEZO1187B99055E', 2008, Decimal('149.86404')),
 ('SOGDBUF12A8C140FAA', 'Intro', 'AR558FS1187FB45658', 2003, Decimal('75.67628')),
 ('SORRZGD12A6310DBC3', 'Harajuku Girls', 'ARVBRGZ1187FB4675A', 2004, Decimal('290.55955')),
 ('SONWXQJ12A8C134D94', 'The Ballad Of Sleeping Beauty', 'ARNF6401187FB57032', 1994, Decimal('305.162')),
 ('SOFCHDR12AB01866EF', 'Living Hell', 'AREVWGE1187B9B890A', 0, Decimal('282.43546'))]

In [8]:
%sql SELECT * FROM artists LIMIT 5;

 * postgresql://student:***@127.0.0.1/sparkifydb
5 rows affected.

[('AR8IEZO1187B99055E', 'Marc Shaiman', '', None, None),
 ('AR558FS1187FB45658', '40 Grit', '', None, None),
 ('ARVBRGZ1187FB4675A', 'Gwen Stefani', '', None, None),
 ('ARNF6401187FB57032', 'Sophie B. Hawkins', 'New York, NY [Manhattan]', Decimal('40.79086'), Decimal('-73.96644')),
 ('AREVWGE1187B9B890A', 'Bitter End', 'Noci (BA)', Decimal('-13.442'), Decimal('-41.9952'))]

In [9]:
%sql SELECT * FROM time LIMIT 5;

 * postgresql://student:***@127.0.0.1/sparkifydb
5 rows affected.

[(datetime.datetime(2018, 11, 29, 0, 0, 57, 796000), 0, 29, 48, 11, 2018, 'Thursday'),
 (datetime.datetime(2018, 11, 29, 0, 1, 30, 796000), 0, 29, 48, 11, 2018, 'Thursday'),
 (datetime.datetime(2018, 11, 29, 0, 4, 1, 796000), 0, 29, 48, 11, 2018, 'Thursday'),
 (datetime.datetime(2018, 11, 29, 0, 4, 55, 796000), 0, 29, 48, 11, 2018, 'Thursday'),
 (datetime.datetime(2018, 11, 29, 0, 7, 13, 796000), 0, 29, 48, 11, 2018, 'Thursday')]

## REMEMBER: Restart this notebook to close connection to `sparkifydb`
Each time you run the cells above, remember to restart this notebook to close the connection to your database. Otherwise, you won't be able to run your code in `create_tables.py`, `etl.py`, or `etl.ipynb` files since you can't make multiple connections to the same database (in this case, sparkifydb

In [1]:
%run create_tables.py

In [2]:
%run etl.py

82 files found in data/song_data
/home/workspace/data/song_data/A/B/C/TRABCRU128F423F449.json
['SOINLJW12A8C13314C', 'City Slickers', 'AR8IEZO1187B99055E', 2008, 149.86404]
1/82 files processed.
/home/workspace/data/song_data/A/B/C/TRABCTK128F934B224.json
['SOGDBUF12A8C140FAA', 'Intro', 'AR558FS1187FB45658', 2003, 75.67628]
2/82 files processed.
/home/workspace/data/song_data/A/B/C/TRABCUQ128E0783E2B.json
['SORRZGD12A6310DBC3', 'Harajuku Girls', 'ARVBRGZ1187FB4675A', 2004, 290.55955]
3/82 files processed.
/home/workspace/data/song_data/A/B/C/TRABCIX128F4265903.json
['SONWXQJ12A8C134D94', 'The Ballad Of Sleeping Beauty', 'ARNF6401187FB57032', 1994, 305.162]
4/82 files processed.
/home/workspace/data/song_data/A/B/C/TRABCYE128F934CE1D.json
['SOFCHDR12AB01866EF', 'Living Hell', 'AREVWGE1187B9B890A', 0, 282.43546]
5/82 files processed.
/home/workspace/data/song_data/A/B/C/TRABCEC128F426456E.json
['SONSKXP12A8C13A2C9', 'Native Soul', 'AR0IAWL1187B9A96D0', 2003, 197.19791]
6/82 files processed.
/home/workspace/data/song_data/A/B/C/TRABCXB128F4286BD3.json
['SODAUVL12A8C13D184', 'Prognosis', 'ARWB3G61187FB49404', 2000, 363.85914]
7/82 files processed.
/home/workspace/data/song_data/A/B/C/TRABCAJ12903CDFCC2.json
['SOSWKAV12AB018FC91', 'Midnight Star', 'ARULZCI1241B9C8611', 0, 335.51628]
8/82 files processed.
/home/workspace/data/song_data/A/B/C/TRABCPZ128F4275C32.json
['SOLYIBD12A8C135045', 'Music is what we love', 'AR051KA1187B98B2FF', 0, 261.51138]
9/82 files processed.
/home/workspace/data/song_data/A/B/C/TRABCKL128F423A778.json
['SOWQTQZ12A58A7B63E', 'Streets On Fire (Explicit Album Version)', 'ARPFHN61187FB575F6', 0, 279.97995]
10/82 files processed.
/home/workspace/data/song_data/A/B/C/TRABCEI128F424C983.json
['SOUPIRU12A6D4FA1E1', 'Der Kleine Dompfaff', 'ARJIE2Y1187B994AB7', 0, 152.92036]
11/82 files processed.
/home/workspace/data/song_data/A/B/C/TRABCFL128F149BB0D.json
['SODREIN12A58A7F2E5', 'A Whiter Shade Of Pale (Live @ Fillmore West)', 'ARLTWXK1187FB5A3F8', 0, 326.00771]
12/82 files processed.
/home/workspace/data/song_data/A/B/C/.ipynb_checkpoints/TRABCEC128F426456E-checkpoint.json
['SONSKXP12A8C13A2C9', 'Native Soul', 'AR0IAWL1187B9A96D0', 2003, 197.19791]
13/82 files processed.
/home/workspace/data/song_data/A/B/C/.ipynb_checkpoints/TRABCAJ12903CDFCC2-checkpoint.json
['SOSWKAV12AB018FC91', 'Midnight Star', 'ARULZCI1241B9C8611', 0, 335.51628]
14/82 files processed.
/home/workspace/data/song_data/A/B/B/TRABBBV128F42967D7.json
['SOBCOSW12A8C13D398', 'Rumba De Barcelona', 'AR7SMBG1187B9B9066', 0, 218.38322]
15/82 files processed.
/home/workspace/data/song_data/A/B/B/TRABBLU128F93349CF.json
['SOFNOQK12AB01840FC', 'Kutt Free (DJ Volume Remix)', 'ARNNKDK1187B98BBD5', 0, 407.37914]
16/82 files processed.
/home/workspace/data/song_data/A/B/B/TRABBXU128F92FEF48.json
['SOXILUQ12A58A7C72A', 'Jenny Take a Ride', 'ARP6N5A1187B99D1A3', 2004, 207.43791]
17/82 files processed.
/home/workspace/data/song_data/A/B/B/TRABBAM128F429D223.json
['SOOJPRH12A8C141995', 'Loaded Like A Gun', 'ARBGXIG122988F409D', 0, 173.19138]
18/82 files processed.
/home/workspace/data/song_data/A/B/B/TRABBJE12903CDB442.json
['SOQOTLQ12AB01868D0', 'Clementina Santafè', 'ARGCY1Y1187B9A4FA5', 0, 153.33832]
19/82 files processed.
/home/workspace/data/song_data/A/B/B/TRABBNP128F932546F.json
['SOGVQGJ12AB017F169', 'Ten Tonne', 'AR62SOJ1187FB47BB5', 2005, 337.68444]
20/82 files processed.
/home/workspace/data/song_data/A/B/B/TRABBOP128F931B50D.json
['SOFFKZS12AB017F194', 'A Higher Place (Album Version)', 'ARBEBBY1187B9B43DB', 1994, 236.17261]
21/82 files processed.
/home/workspace/data/song_data/A/B/B/TRABBZN12903CD9297.json
['SOTCKKY12AB018A141', 'Sonnerie lalaleulé hi houuu', 'ARGSAFR1269FB35070', 0, 29.54404]
22/82 files processed.
/home/workspace/data/song_data/A/B/B/TRABBOR128F4286200.json
['SOBAYLL12A8C138AF9', 'Sono andati? Fingevo di dormire', 'ARDR4AC1187FB371A1', 0, 511.16363]
23/82 files processed.
/home/workspace/data/song_data/A/B/B/TRABBTA128F933D304.json
['SOLEYHO12AB0188A85', 'Got My Mojo Workin', 'ARAGB2O1187FB3A161', 0, 338.23302]
24/82 files processed.
/home/workspace/data/song_data/A/B/B/TRABBKX128F4285205.json
['SOBKWDJ12A8C13B2F3', 'Wild Rose (Back 2 Basics Mix)', 'AR36F9J1187FB406F1', 0, 230.71302]
25/82 files processed.
/home/workspace/data/song_data/A/B/B/TRABBVJ128F92F7EAA.json
['SOPEGZN12AB0181B3D', 'Get Your Head Stuck On Your Neck', 'AREDL271187FB40F44', 0, 45.66159]
26/82 files processed.
/home/workspace/data/song_data/A/B/B/.ipynb_checkpoints/TRABBBV128F42967D7-checkpoint.json
['SOBCOSW12A8C13D398', 'Rumba De Barcelona', 'AR7SMBG1187B9B9066', 0, 218.38322]
27/82 files processed.
/home/workspace/data/song_data/A/B/A/TRABACN128F425B784.json
['SOQLGFP12A58A7800E', 'OAKtown', 'ARD7TVE1187B99BFB1', 0, 259.44771]
28/82 files processed.
/home/workspace/data/song_data/A/B/A/TRABAWW128F4250A31.json
['SOMVWWT12A58A7AE05', 'Knocked Out Of The Park', 'ARQ9BO41187FB5CF1F', 0, 183.17016]
29/82 files processed.
/home/workspace/data/song_data/A/B/A/TRABATO128F42627E9.json
['SOSLAVG12A8C13397F', 'Den Pai Alo', 'AROGWRA122988FEE45', 0, 243.82649]
30/82 files processed.
/home/workspace/data/song_data/A/B/A/TRABAXL128F424FC50.json
['SOQVMXR12A81C21483', 'Salt In NYC', 'ARKULSX1187FB45F84', 0, 424.12363]
31/82 files processed.
/home/workspace/data/song_data/A/B/A/TRABAFJ128F42AF24E.json
['SOPVXLX12A8C1402D5', 'Larger Than Life', 'AR3JMC51187B9AE49D', 1999, 236.25098]
32/82 files processed.
/home/workspace/data/song_data/A/B/A/TRABAXR128F426515F.json
['SODUJBS12A8C132150', 'Wessex Loses a Bride', 'ARI2JSK1187FB496EF', 0, 111.62077]
33/82 files processed.
/home/workspace/data/song_data/A/B/A/TRABAXV128F92F6AE3.json
['SOBBXLX12A58A79DDA', 'Erica (2005 Digital Remaster)', 'AREDBBQ1187B98AFF5', 0, 138.63138]
34/82 files processed.
/home/workspace/data/song_data/A/B/A/TRABAZH128F930419A.json
['SOTUKVB12AB0181477', 'Blessed Assurance', 'AR7ZKHQ1187B98DD73', 1993, 270.602]
35/82 files processed.
/home/workspace/data/song_data/A/B/A/TRABAFP128F931E9A1.json
['SOAOIBZ12AB01815BE', 'I Hold Your Hand In Mine [Live At Royal Albert Hall]', 'ARPBNLO1187FB3D52F', 2000, 43.36281]
36/82 files processed.
/home/workspace/data/song_data/A/B/A/TRABAIO128F42938F9.json
['SOZHPGD12A8C1394FE', 'Baby Come To Me', 'AR9AWNF1187B9AB0B4', 0, 236.93016]
37/82 files processed.
/home/workspace/data/song_data/A/B/A/TRABAVQ12903CBF7E0.json
['SOTTDKS12AB018D69B', 'It Wont Be Christmas', 'ARMBR4Y1187B9990EB', 0, 241.47546]
38/82 files processed.
/home/workspace/data/song_data/A/A/C/TRAACFV128F935E50B.json
['SOBLGCN12AB0183212', 'James (Hold The Ladder Steady)', 'AR47JEX1187B995D81', 1985, 124.86485]
39/82 files processed.
/home/workspace/data/song_data/A/A/C/TRAACLV128F427E123.json
['SONYPOM12A8C13B2D7', 'I Think My Wife Is Running Around On Me (Taco Hell)', 'ARDNS031187B9924F0', 2005, 186.48771]
40/82 files processed.
/home/workspace/data/song_data/A/A/C/TRAACVS128E078BE39.json
['SOOLYAZ12A6701F4A6', 'Laws Patrolling (Album Version)', 'AREBBGV1187FB523D2', 0, 173.66159]
41/82 files processed.
/home/workspace/data/song_data/A/A/C/TRAACHN128F1489601.json
['SOPSWQW12A6D4F8781', 'Made Like This (Live)', 'ARGIWFO1187B9B55B7', 0, 225.09669]
42/82 files processed.
/home/workspace/data/song_data/A/A/C/TRAACSL128F93462F4.json
['SOYTPEP12AB0180E7B', 'Twist and Shout', 'ARAJPHH1187FB5566A', 1964, 164.80608]
43/82 files processed.
/home/workspace/data/song_data/A/A/C/TRAACTB12903CAAF15.json
['SOGXHEG12AB018653E', 'It Makes No Difference Now', 'AR0RCMP1187FB3F427', 1992, 133.32853]
44/82 files processed.
/home/workspace/data/song_data/A/A/C/TRAACOW128F933E35F.json
['SOVYKGO12AB0187199', 'Crazy Mixed Up World', 'ARH4Z031187B9A71F2', 1961, 156.39465]
45/82 files processed.
/home/workspace/data/song_data/A/A/C/TRAACPE128F421C1B9.json
['SOGNCJP12A58A80271', 'Do You Finally Need A Friend', 'ARB29H41187B98F0EF', 1972, 342.56934]
46/82 files processed.
/home/workspace/data/song_data/A/A/C/TRAACZK128F4243829.json
['SOGOSOV12AF72A285E', '¿Dónde va Chichi?', 'ARGUVEV1187B98BA17', 1997, 313.12934]
47/82 files processed.
/home/workspace/data/song_data/A/A/C/TRAACQT128F9331780.json
['SOLLHMX12AB01846DC', 'The Emperor Falls', 'AR1Y2PT1187FB5B9CE', 0, 484.62322]
48/82 files processed.
/home/workspace/data/song_data/A/A/C/TRAACNS128F14A2DF5.json
['SOBZBAZ12A6D4F8742', 'Spanish Grease', 'AROUOZZ1187B9ABE51', 1997, 168.25424]
49/82 files processed.
/home/workspace/data/song_data/A/A/C/TRAACIW12903CC0F6D.json
['SOZQDIU12A58A7BCF6', 'Superconfidential', 'ARNTLGG11E2835DDB9', 0, 338.31138]
50/82 files processed.
/home/workspace/data/song_data/A/A/C/TRAACCG128F92E8A55.json
['SOZCTXZ12AB0182364', 'Setanta matins', 'AR5KOSW1187FB35FF4', 0, 269.58322]
51/82 files processed.
/home/workspace/data/song_data/A/A/C/TRAACER128F4290F96.json
['SOBBUGU12A8C13E95D', 'Setting Fire to Sleeping Giants', 'ARMAC4T1187FB3FA4C', 2004, 207.77751]
52/82 files processed.
/home/workspace/data/song_data/A/A/C/.ipynb_checkpoints/TRAACER128F4290F96-checkpoint.json
['SOBBUGU12A8C13E95D', 'Setting Fire to Sleeping Giants', 'ARMAC4T1187FB3FA4C', 2004, 207.77751]
53/82 files processed.
/home/workspace/data/song_data/A/A/C/.ipynb_checkpoints/TRAACHN128F1489601-checkpoint.json
['SOPSWQW12A6D4F8781', 'Made Like This (Live)', 'ARGIWFO1187B9B55B7', 0, 225.09669]
54/82 files processed.
/home/workspace/data/song_data/A/A/C/.ipynb_checkpoints/TRAACLV128F427E123-checkpoint.json
['SONYPOM12A8C13B2D7', 'I Think My Wife Is Running Around On Me (Taco Hell)', 'ARDNS031187B9924F0', 2005, 186.48771]
55/82 files processed.
/home/workspace/data/song_data/A/A/C/.ipynb_checkpoints/TRAACQT128F9331780-checkpoint.json
['SOLLHMX12AB01846DC', 'The Emperor Falls', 'AR1Y2PT1187FB5B9CE', 0, 484.62322]
56/82 files processed.
/home/workspace/data/song_data/A/A/C/.ipynb_checkpoints/TRAACCG128F92E8A55-checkpoint.json
['SOZCTXZ12AB0182364', 'Setanta matins', 'AR5KOSW1187FB35FF4', 0, 269.58322]
57/82 files processed.
/home/workspace/data/song_data/A/A/B/TRAABNV128F425CEE1.json
['SOUQQEA12A8C134B1B', 'High Tide', 'ARIG6O41187B988BDD', 0, 228.5971]
58/82 files processed.
/home/workspace/data/song_data/A/A/B/TRAABJV128F1460C49.json
['SOBONFF12A6D4F84D8', 'Tonight Will Be Alright', 'ARIK43K1187B9AE54C', 1986, 307.3824]
59/82 files processed.
/home/workspace/data/song_data/A/A/B/TRAABVM128F92CA9DC.json
['SOXLBJT12A8C140925', 'Caught In A Dream', 'ARYKCQI1187FB3B18F', 2004, 290.29832]
60/82 files processed.
/home/workspace/data/song_data/A/A/B/TRAABLR128F423B7E3.json
['SOHUOAP12A8AE488E9', 'Floating', 'ARD842G1187B997376', 1987, 491.12771]
61/82 files processed.
/home/workspace/data/song_data/A/A/B/TRAABCL128F4286650.json
['SOKEJEJ12A8C13E0D0', 'The Urgency (LP Version)', 'ARC43071187B990240', 0, 245.21098]
62/82 files processed.
/home/workspace/data/song_data/A/A/B/TRAABDL12903CAABBA.json
['SOMUYGI12AB0188633', 'La Culpa', 'ARL7K851187B99ACD2', 0, 226.35057]
63/82 files processed.
/home/workspace/data/song_data/A/A/B/TRAABXG128F9318EBD.json
['SOZVMJI12AB01808AF', 'Synthetic Dream', 'ARNPAGP1241B9C7FD4', 0, 165.69424]
64/82 files processed.
/home/workspace/data/song_data/A/A/B/TRAABYN12903CFD305.json
['SOWTBJW12AC468AC6E', 'Broken-Down Merry-Go-Round', 'ARQGYP71187FB44566', 0, 151.84934]
65/82 files processed.
/home/workspace/data/song_data/A/A/B/TRAABRB128F9306DD5.json
['SOILPQQ12AB017E82A', 'Sohna Nee Sohna Data', 'AR1ZHYZ1187FB3C717', 0, 599.24853]
66/82 files processed.
/home/workspace/data/song_data/A/A/B/TRAABJL12903CDCF1A.json
['SORAMLE12AB017C8B0', 'Auguri Cha Cha', 'ARHHO3O1187B989413', 0, 191.84281]
67/82 files processed.
/home/workspace/data/song_data/A/A/B/TRAABYW128F4244559.json
['SOBEBDG12A58A76D60', 'Kassie Jones', 'ARI3BMM1187FB4255E', 0, 220.78649]
68/82 files processed.
/home/workspace/data/song_data/A/A/B/.ipynb_checkpoints/TRAABNV128F425CEE1-checkpoint.json
['SOUQQEA12A8C134B1B', 'High Tide', 'ARIG6O41187B988BDD', 0, 228.5971]
69/82 files processed.
/home/workspace/data/song_data/A/A/B/.ipynb_checkpoints/TRAABDL12903CAABBA-checkpoint.json
['SOMUYGI12AB0188633', 'La Culpa', 'ARL7K851187B99ACD2', 0, 226.35057]
70/82 files processed.
/home/workspace/data/song_data/A/A/B/.ipynb_checkpoints/TRAABYN12903CFD305-checkpoint.json
['SOWTBJW12AC468AC6E', 'Broken-Down Merry-Go-Round', 'ARQGYP71187FB44566', 0, 151.84934]
71/82 files processed.
/home/workspace/data/song_data/A/A/A/TRAAADZ128F9348C2E.json
['SOXVLOJ12AB0189215', 'Amor De Cabaret', 'ARKRRTF1187B9984DA', 0, 177.47546]
72/82 files processed.
/home/workspace/data/song_data/A/A/A/TRAAARJ128F9320760.json
['SOIAZJW12AB01853F1', 'Pink World', 'AR8ZCNI1187B9A069B', 1984, 269.81832]
73/82 files processed.
/home/workspace/data/song_data/A/A/A/TRAAAPK128E0786D96.json
['SOHKNRJ12A6701D1F8', 'Drop of Rain', 'AR10USD1187B99F3F1', 0, 189.57016]
74/82 files processed.
/home/workspace/data/song_data/A/A/A/TRAAAVG12903CFA543.json
['SOUDSGM12AC9618304', 'Insatiable (Instrumental Version)', 'ARNTLGG11E2835DDB9', 0, 266.39628]
75/82 files processed.
/home/workspace/data/song_data/A/A/A/TRAAAFD128F92F423A.json
['SOFSOCN12A8C143F5D', 'Face the Ashes', 'ARXR32B1187FB57099', 2007, 209.60608]
76/82 files processed.
/home/workspace/data/song_data/A/A/A/TRAAAVO128F93133D4.json
['SOQHXMF12AB0182363', 'Young Boy Blues', 'ARGSJW91187B9B1D6B', 0, 218.77506]
77/82 files processed.
/home/workspace/data/song_data/A/A/A/TRAAAAW128F429D538.json
['SOMZWCG12A8C13C480', "I Didn't Mean To", 'ARD7TVE1187B99BFB1', 0, 218.93179]
78/82 files processed.
/home/workspace/data/song_data/A/A/A/TRAAAEF128F4273421.json
['SONHOTT12A8C13493C', 'Something Girls', 'AR7G5I41187FB4CE6C', 1982, 233.40363]
79/82 files processed.
/home/workspace/data/song_data/A/A/A/TRAAAMQ128F1460CD3.json
['SOMJBYD12A6D4F8557', 'Keepin It Real (Skit)', 'ARD0S291187B9B7BF5', 0, 114.78159]
80/82 files processed.
/home/workspace/data/song_data/A/A/A/TRAAAMO128F1481E7F.json
['SOYMRWW12A6D4FAB14', 'The Moon And I (Ordinary Day Album Version)', 'ARKFYS91187B98E58F', 0, 267.7024]
81/82 files processed.
/home/workspace/data/song_data/A/A/A/TRAAABD128F429CF47.json
['SOCIWDW12A8C13D406', 'Soul Deep', 'ARMJAGH1187FB546F3', 1969, 148.03546]
82/82 files processed.
34 files found in data/log_data
1/34 files processed.
2/34 files processed.
3/34 files processed.
4/34 files processed.
5/34 files processed.
6/34 files processed.
7/34 files processed.
8/34 files processed.
9/34 files processed.
10/34 files processed.
11/34 files processed.
12/34 files processed.
13/34 files processed.
14/34 files processed.
15/34 files processed.
16/34 files processed.
17/34 files processed.
18/34 files processed.
19/34 files processed.
20/34 files processed.
21/34 files processed.
22/34 files processed.
23/34 files processed.
24/34 files processed.
25/34 files processed.
26/34 files processed.
27/34 files processed.
28/34 files processed.
29/34 files processed.
30/34 files processed.
31/34 files processed.
32/34 files processed.
33/34 files processed.
34/34 files processed.